# Generated by Django 2.2.5 on 2019-09-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='tel_number',
            new_name='phone_number',
        ),
    ]
