# Generated by Django 2.2.5 on 2019-09-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency', models.DecimalField(decimal_places=4, max_digits=10)),
                ('write_of_acc', models.CharField(max_length=30)),
                ('receipt_acc', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('denied', 'denied'), ('accepted', 'accepted')], max_length=10)),
            ],
        ),
    ]
