# Generated by Django 2.2.5 on 2019-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('currency', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creating', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deals',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='user',
        ),
        migrations.AlterField(
            model_name='deals',
            name='status',
            field=models.CharField(choices=[('Denied', 'denied'), ('Sccepted', 'accepted'), ('Saved', 'saved')], max_length=10),
        ),
    ]
